enable-magisk-update = false
parallel-jobs = 1

cli-source = "MorpheApp/morphe-cli"
cli-version = "latest"

# https://github.com/ReVanced/where-is-revanced-patches
# [Infinity]
# patcher-args = "-e 'Spoof client' -Oclient-id=$ID"
# cli-source = "ReVanced/revanced-cli"
# cli-version = "v5.0.1"
# patches-source = "ReVanced/revanced-patches"
# patches-version = "v5.50.2"
# arch = "arm64-v8a"

# 403 CF error
# apkmirror-dlurl = "https://apkmirror.com/apk/docile-alligator/infinity-for-reddit/"
# uptodown-dlurl = "https://infinity-for-reddit.en.uptodown.com/android"


[YouTube]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
patches-version = "latest"
arch = "arm64-v8a"
riplib = false
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.youtube"

# 403 CF error
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"


[YouTube-Music]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
patches-version = "latest"
arch = "arm64-v8a"
riplib = false
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.apps.youtube.music"

# 403 CF error
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
