enable-magisk-update = false
parallel-jobs = 1

cli-source = "MorpheApp/morphe-cli"
cli-version = "latest"


[YouTube]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
patches-version = "latest"
riplib = false
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.youtube"

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"


[YouTube-Music]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
patches-version = "latest"
riplib = false
patcher-args = "-e 'Change package name' -OpackageName=app.revanced.android.apps.youtube.music"

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
